---
title: "discharge_time_series"
output: html_document
date: "2022-08-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dataRetrieval)
library(janitor)
```


https://waterdata.usgs.gov/nwis/uv?site_no=11118500

prompt: https://brunj7.github.io/EDS-214-analytical-workflows/day3-apis.html#Hands-on
```{r}

# Choptank River near Greensboro, MD
siteNumber <- "11118500" 
VenturaInfo <- readNWISsite(siteNumber)
parameterCd <- "00060"

#Raw daily data:
rawDailyData <- readNWISdv(siteNumber,parameterCd,
                      "2019-10-01","2020-10-05") %>% 
  clean_names()

```


plot the discharge time series
```{r}
discharge_plot <- ggplot(rawDailyData, aes(x = date, y = x_00060_00003)) +
  geom_line() +
  labs(x = "date", y = "discharge") 
```




Exercise 2

```{r}
# set inputs
data_obj <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"
path <- "~/R/eds214_day3_api_practice"

# download data and metadata
library(metajam)
download_d1_data(data_obj, path)

```

Read in the data
```{r}
household_data <- read_d1_files("~/R/eds214_day3_api_practice/doi_10.5063_F1CJ8BPH__household_language__csv")
```

```{r}
household_df <- household_data$data
```

write code that will compute the percentage of Alaskan household speaking only English from 2009-2015
```{r}
percentage <- household_df %>% 
  select()
```

